import { calculateSustainabilityTier, TIERS } from "./benchmarks";
import { calculateEmpiricalPercentile } from "./percentiles";

/**
 * Statistics regarding a user's standing within the CarbonWise community.
 */
export interface CommunityStats {
  averageScore: number;
  top10Score: number;
  top25Score: number;
  userScore: number;
  userRank: "Top 10%" | "Top 25%" | "Top 50%" | "Bottom 50%";
  userPercentile: number; // e.g. 77 for "better than 77%"
}

/**
 * Calculates community ranking based on a user's score and a list of historical/community scores.
 * For MVP purposes, if the community history is too small, we inject realistic mock data to simulate a user base.
 * 
 * @param userScore The user's current sustainability score (0-100)
 * @param communityScores An array of all recorded community scores
 * @returns An object containing percentile metrics and threshold scores for the community
 * 
 * @example
 * const stats = calculateCommunityRanking(85, [50, 60, 70, 80, 90]);
 * console.log(stats.userPercentile); // 80
 */
export function calculateCommunityRanking(userScore: number, communityScores: number[]): CommunityStats {
  // Inject mock community data if we don't have a real backend to make the MVP look populated
  let allScores = [...communityScores];
  if (allScores.length < 20) {
    const mockScores = [45, 52, 58, 61, 65, 68, 70, 71, 72, 75, 78, 80, 82, 85, 88, 91, 93, 95];
    allScores = [...allScores, ...mockScores];
  }
  
  // Sort descending
  allScores.sort((a, b) => b - a);

  const averageScore = Math.round(allScores.reduce((a, b) => a + b, 0) / allScores.length);
  
  const top10Index = Math.max(0, Math.floor(allScores.length * 0.1) - 1);
  const top25Index = Math.max(0, Math.floor(allScores.length * 0.25) - 1);

  const top10Score = allScores[top10Index];
  const top25Score = allScores[top25Index];

  // Calculate percentile
  const userPercentile = calculateEmpiricalPercentile(userScore, allScores);

  let userRank: CommunityStats["userRank"] = "Bottom 50%";
  if (userScore >= top10Score) userRank = "Top 10%";
  else if (userScore >= top25Score) userRank = "Top 25%";
  else if (userScore >= averageScore) userRank = "Top 50%";

  return {
    averageScore,
    top10Score,
    top25Score,
    userScore,
    userRank,
    userPercentile
  };
}

/**
 * Generates natural language insights explaining a user's community ranking.
 * 
 * @param stats The community stats generated by calculateCommunityRanking
 * @returns An array of string insights highlighting rank proximity and achievements
 */
export function calculateCommunityInsights(stats: CommunityStats): string[] {
  const insights: string[] = [];

  insights.push(`🌱 You're performing better than ${stats.userPercentile}% of CarbonWise users.`);

  if (stats.userScore < stats.top10Score && stats.userScore >= stats.top25Score) {
    insights.push(`🏆 You're only ${stats.top10Score - stats.userScore} points away from the Top 10%.`);
  } else if (stats.userScore < stats.top25Score && stats.userScore >= stats.averageScore) {
    insights.push(`📈 You're ${stats.top25Score - stats.userScore} points away from the Top 25%.`);
  } else if (stats.userScore < stats.averageScore) {
    insights.push(`💡 You're ${stats.averageScore - stats.userScore} points away from the community average.`);
  } else {
    insights.push(`🌟 You are among the elite Top 10% of our community!`);
  }

  insights.push(`🎯 Improving transportation habits could move you into the top sustainability tier.`); // Static example as requested by prompt

  return insights;
}

/**
 * Represents the progress required to reach the next sustainability tier.
 */
export interface TierProgress {
  currentTier: string;
  nextTier: string | null;
  reductionNeeded: number; // in kg CO2
  progressPercent: number;
}

/**
 * Calculates how close the user is to graduating to the next sustainability tier.
 * 
 * @param currentFootprint The user's annual carbon footprint in kg CO₂/year
 * @returns An object detailing the current tier, the next target tier, and percentage progress
 * 
 * @example
 * const progress = calculateNextTierProgress(1800);
 * console.log(`You need to reduce ${progress.reductionNeeded} kg to reach ${progress.nextTier}`);
 */
export function calculateNextTierProgress(currentFootprint: number): TierProgress {
  const currentTier = calculateSustainabilityTier(currentFootprint);
  const currentIndex = TIERS.findIndex(t => t.name === currentTier.name);
  
  if (currentIndex <= 0) {
    return {
      currentTier: currentTier.name,
      nextTier: null,
      reductionNeeded: 0,
      progressPercent: 100
    };
  }

  const nextTier = TIERS[currentIndex - 1];
  const nextTierThreshold = nextTier.max; 
  
  const currentTierBase = TIERS[currentIndex].max; 
  // e.g. Eco Leader (max 2000), current 2500, Green Learner (max 4000)
  // Distance to next tier = currentFootprint - nextTierThreshold
  
  const reductionNeeded = Math.max(0, currentFootprint - nextTierThreshold);
  
  // Total span of current tier
  // If current is Eco Leader (2000-4000). Max is 4000, next threshold is 2000.
  // We are at 2500. We covered (4000 - 2500) = 1500 of the 2000 span.
  const tierSpan = currentTierBase - nextTierThreshold;
  const progressMade = currentTierBase - currentFootprint;
  
  let progressPercent = 0;
  if (tierSpan > 0) {
    progressPercent = Math.max(0, Math.min(100, Math.round((progressMade / tierSpan) * 100)));
  }

  return {
    currentTier: currentTier.name,
    nextTier: nextTier.name,
    reductionNeeded,
    progressPercent
  };
}
