import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Zap } from "lucide-react";

interface Recommendation {
  id: string;
  recommendation: string;
  estimatedSavings: number;
}

interface DashboardAIRecommendationsProps {
  recommendations: Recommendation[];
}

export function DashboardAIRecommendations({ recommendations }: DashboardAIRecommendationsProps) {
  return (
    <Card className="col-span-1 md:col-span-3 border-blue-200 dark:border-blue-900 bg-blue-50/50 dark:bg-blue-900/10 rounded-3xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-blue-800 dark:text-blue-300">
          <Zap className="w-6 h-6 text-blue-500" />
          AI Sustainability Coach
        </CardTitle>
        <CardDescription>Personalized insights generated by Gemini AI</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {recommendations.length > 0 ? (
            recommendations.map((rec) => (
              <div key={rec.id} className="p-5 bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800 hover:shadow-md transition-shadow">
                <p className="font-medium text-slate-800 dark:text-slate-200 mb-4">{rec.recommendation}</p>
                <div className="flex justify-between items-center text-sm">
                  <span className="text-green-600 font-semibold bg-green-100 dark:bg-green-900/30 px-3 py-1 rounded-full">
                    Save {rec.estimatedSavings} kg CO₂
                  </span>
                </div>
              </div>
            ))
          ) : (
            <p className="text-slate-500">Generating personalized insights... Check back soon.</p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
